#!/usr/bin/env python3
"""
log_analyzer.py
Parses raw SOC log files (firewall, auth, IDS), correlates related events into
incidents, and classifies each one into a ticket with:
  - severity (critical/high/medium/low)
  - category
  - title
  - raw evidence (the source log lines) and metadata (src/dst/user/count)
  - ticket status (defaults to "open")

This script only classifies alerts -- it does NOT write the description or
recommended action text. Those are generated by an LLM in the next pipeline
stage (llm_enrich.py), so the analyst-facing writeup is always AI-authored
based on the real evidence, not a canned template.

Usage:
    python3 log_analyzer.py
Reads from ./logs/*.log, writes ./tickets.json
"""

import re
import json
import hashlib
from collections import defaultdict
from datetime import datetime

LOG_DIR = "logs"
OUTPUT_FILE = "tickets.json"

# -----------------------------------------------------------------------
# Parsers -- one regex per log format, tolerant of the fields we care about
# -----------------------------------------------------------------------

FW_RE = re.compile(
    r"^(?P<ts>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s+\S+\s+kernel:\s+"
    r"ACTION=(?P<action>\w+)\s+PROTO=(?P<proto>\w+)\s+SRC=(?P<src>[\d.]+)\s+"
    r"DST=(?P<dst>[\d.]+)\s+SPT=(?P<spt>\d+)\s+DPT=(?P<dpt>\d+)"
)

AUTH_RE = re.compile(
    r"^(?P<ts>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s+\S+\s+sshd\[\d+\]:\s+"
    r"(?P<result>Accepted|Failed)\s+password\s+for\s+(?P<user>\"[^\"]+\"|\S+)\s+from\s+"
    r"(?P<src>[\d.]+)\s+port\s+(?P<port>\d+)"
)

IDS_RE = re.compile(
    r"^(?P<ts>[\d/]+-[\d:.]+)\s+\[\*\*\]\s+\[\d+:(?P<sid>\d+):\d+\]\s+"
    r"(?P<msg>.+?)\s+\[\*\*\]\s+\[Classification:\s(?P<classification>[^\]]+)\]\s+"
    r"\[Priority:\s(?P<priority>\d+)\]\s+\{(?P<proto>\w+)\}\s+(?P<src>[\d.]+):(?P<sport>\d+)\s+->\s+"
    r"(?P<dst>[\d.]+):(?P<dport>\d+)"
)


def parse_firewall(path):
    events = []
    with open(path) as f:
        for line in f:
            m = FW_RE.match(line.strip())
            if m:
                events.append({**m.groupdict(), "raw": line.strip(), "source": "firewall"})
    return events


def parse_auth(path):
    events = []
    with open(path) as f:
        for line in f:
            m = AUTH_RE.match(line.strip())
            if m:
                events.append({**m.groupdict(), "raw": line.strip(), "source": "auth"})
    return events


def parse_ids(path):
    events = []
    with open(path) as f:
        for line in f:
            m = IDS_RE.match(line.strip())
            if m:
                events.append({**m.groupdict(), "raw": line.strip(), "source": "ids"})
    return events


# -----------------------------------------------------------------------
# Ticket helper
# -----------------------------------------------------------------------

def make_ticket_id(*parts):
    h = hashlib.sha1("|".join(parts).encode()).hexdigest()[:8]
    return f"TCK-{h.upper()}"


def new_ticket(first_ts, severity, category, title,
               evidence, src=None, dst=None, user=None, count=1, id_seed=None):
    return {
        "id": make_ticket_id(id_seed or title, first_ts, src or ""),
        "timestamp": first_ts,
        "severity": severity,          # critical | high | medium | low | info
        "category": category,
        "title": title,
        "description": "",             # filled in by llm_enrich.py
        "recommended_action": "",      # filled in by llm_enrich.py
        "src_ip": src,
        "dst_ip": dst,
        "user": user,
        "event_count": count,
        "evidence": evidence[:10],     # cap stored raw lines to keep payload sane
        "status": "open",              # open | closed | forwarded
        "forwarded_to": None,
        "analyst_notes": "",
    }


# -----------------------------------------------------------------------
# Correlation / detection rules
# -----------------------------------------------------------------------

def detect_port_scans(fw_events, threshold=15, window_ports=10):
    """Same SRC hitting many distinct DPT on the same DST -> port scan."""
    tickets = []
    by_src_dst = defaultdict(list)
    for e in fw_events:
        if e["action"] == "DENY":
            by_src_dst[(e["src"], e["dst"])].append(e)

    for (src, dst), evs in by_src_dst.items():
        distinct_ports = {e["dpt"] for e in evs}
        if len(distinct_ports) >= window_ports and len(evs) >= threshold:
            evs.sort(key=lambda e: e["ts"])
            tickets.append(new_ticket(
                first_ts=evs[0]["ts"],
                severity="high",
                category="Port Scan",
                title=f"Port scan detected from {src} against {dst}",
                evidence=[e["raw"] for e in evs],
                src=src, dst=dst, count=len(evs),
                id_seed="portscan",
            ))
    return tickets


def detect_moderate_denies(fw_events, min_count=5, max_count=14, min_ports=3):
    """Smaller deny bursts that don't meet the full port-scan threshold -- worth a look."""
    tickets = []
    by_src_dst = defaultdict(list)
    for e in fw_events:
        if e["action"] == "DENY":
            by_src_dst[(e["src"], e["dst"])].append(e)

    for (src, dst), evs in by_src_dst.items():
        distinct_ports = {e["dpt"] for e in evs}
        if min_count <= len(evs) < max_count and len(distinct_ports) >= min_ports:
            evs.sort(key=lambda e: e["ts"])
            tickets.append(new_ticket(
                first_ts=evs[0]["ts"],
                severity="medium",
                category="Suspicious Traffic",
                title=f"Repeated connection denials from {src} to {dst}",
                evidence=[e["raw"] for e in evs],
                src=src, dst=dst, count=len(evs),
                id_seed="modscan",
            ))
    return tickets


def detect_moderate_auth_failures(auth_events, min_count=3, max_count=9):
    """Failed logins below the brute-force threshold -- low/medium noise worth a glance."""
    tickets = []
    by_src = defaultdict(list)
    for e in auth_events:
        if e["result"] == "Failed":
            by_src[e["src"]].append(e)

    for src, evs in by_src.items():
        if min_count <= len(evs) < max_count:
            users = sorted({e["user"] for e in evs})
            tickets.append(new_ticket(
                first_ts=evs[0]["ts"],
                severity="low",
                category="Authentication Anomaly",
                title=f"Multiple failed logins from {src}",
                evidence=[e["raw"] for e in evs],
                src=src, user=", ".join(users), count=len(evs),
                id_seed="authanomaly",
            ))
    return tickets


def detect_bruteforce(auth_events, threshold=10, window_seconds=300):
    """Many Failed logins from the same src in a tight window -> brute force."""
    tickets = []
    by_src = defaultdict(list)
    for e in auth_events:
        if e["result"] == "Failed":
            by_src[e["src"]].append(e)

    for src, evs in by_src.items():
        if len(evs) >= threshold:
            users = sorted({e["user"] for e in evs})
            # check if a success from same src followed
            success_after = any(
                a["result"] == "Accepted" and a["src"] == src for a in auth_events
            )
            severity = "critical" if success_after else "high"
            title = f"SSH brute-force from {src}" + (" — followed by successful login" if success_after else "")
            tickets.append(new_ticket(
                first_ts=evs[0]["ts"],
                severity=severity,
                category="Brute Force / Credential Access",
                title=title,
                evidence=[e["raw"] for e in evs],
                src=src, user=", ".join(users), count=len(evs),
                id_seed="bruteforce",
            ))
    return tickets


IDS_SEVERITY_MAP = {"1": "critical", "2": "high", "3": "low"}


def detect_ids_alerts(ids_events, beacon_min_count=5):
    tickets = []
    by_sig_pair = defaultdict(list)
    for e in ids_events:
        key = (e["sid"], e["src"], e["dst"])
        by_sig_pair[key].append(e)

    for (sid, src, dst), evs in by_sig_pair.items():
        prio = evs[0]["priority"]
        severity = IDS_SEVERITY_MAP.get(prio, "medium")
        msg = evs[0]["msg"]

        # skip pure noise / low-priority policy alerts unless volume is high
        if severity == "low" and len(evs) < 20:
            continue

        is_beacon = "Beacon" in msg and len(evs) >= beacon_min_count
        title = f"{msg} — {src} → {dst}"
        if is_beacon:
            title += f" ({len(evs)} check-ins)"
            severity = "critical"

        tickets.append(new_ticket(
            first_ts=evs[0]["ts"],
            severity=severity,
            category="IDS Alert",
            title=title,
            evidence=[e["raw"] for e in evs],
            src=src, dst=dst, count=len(evs),
            id_seed=f"ids-{sid}",
        ))
    return tickets


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------

def main():
    fw_events = parse_firewall(f"{LOG_DIR}/firewall.log")
    auth_events = parse_auth(f"{LOG_DIR}/auth.log")
    ids_events = parse_ids(f"{LOG_DIR}/ids.log")

    print(f"Parsed: {len(fw_events)} firewall, {len(auth_events)} auth, {len(ids_events)} IDS events")

    tickets = []
    tickets += detect_port_scans(fw_events)
    tickets += detect_moderate_denies(fw_events)
    tickets += detect_bruteforce(auth_events)
    tickets += detect_moderate_auth_failures(auth_events)
    tickets += detect_ids_alerts(ids_events)

    # sort newest-looking first isn't meaningful across formats/timezones here,
    # so sort by severity rank then by raw timestamp string as a tiebreaker
    sev_rank = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    tickets.sort(key=lambda t: (sev_rank.get(t["severity"], 5), t["timestamp"]))

    with open(OUTPUT_FILE, "w") as f:
        json.dump(tickets, f, indent=2)

    print(f"Generated {len(tickets)} tickets -> {OUTPUT_FILE}")
    by_sev = defaultdict(int)
    for t in tickets:
        by_sev[t["severity"]] += 1
    for sev in ["critical", "high", "medium", "low", "info"]:
        if by_sev[sev]:
            print(f"  {sev:9s}: {by_sev[sev]}")


if __name__ == "__main__":
    main()
